fonts:
        - playfair
        - timesnewroman
backgrounds:
        - clouds
                x: 0
                y: 0
                zoom: 1.2
        - abstract
                x: 120
                y: 0
                zoom 0.95



